### ISSUE TITLE
Not seeing search results

### ISSUE THREAD

**Issue by jyavorska** [assemblylanguage/lunadon#2]
I'm using Chrome `Version 99.0.4844.84 (Official Build) (arm64)` on OS X 12.3.1 and my search results pane doesn't seem to show any content. It just shows a blank panel as follows:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/3529318/161229896-89b4a438-542b-45df-8c58-e51b7b47f96b.png">

If I open the developer console I can see a search result come back and images loaded, so I guess it's something to do with the CSS? But not sure.

**Comment by assemblylanguage** [comment]
Thanks for the heads up. Should be fixed from the most recent commit, was a CSS issue with the search result widget.
